### ISSUE TITLE
Data formatting

### ISSUE THREAD

**Issue by hamza13-12** [norahollenstein/zuco-benchmark#4]
Hi. I want to download the dataset and set it up nicely into a dataframe where one column corresponds to eeg signals and the other column corressponds to the sentence. So that way, I can format it into a EEG-Text based dataset and use seq 2 seq models to generate text given an EEG signal. Please provide me with the basic steps to set up your data in this manner

**Comment by samuki** [comment]
Hi, the first step would be to download the whole dataset, using `get_data.sh`.
You could then take a look at the (sentence-level) feature extraction function, which will be called if you run `benchmark_baseline.py`: https://github.com/norahollenstein/zuco-benchmark/blob/5ad276d2d075a30e8a47488cff082df435870ce3/src/extract_features.py#L95

From that function, you can save the sentence [line 117](https://github.com/norahollenstein/zuco-benchmark/blob/5ad276d2d075a30e8a47488cff082df435870ce3/src/extract_features.py#L117) and EEG-features [line 180](https://github.com/norahollenstein/zuco-benchmark/blob/5ad276d2d075a30e8a47488cff082df435870ce3/src/extract_features.py#L180).

Note that these are sentence-level features. If you want to extract word-level features, you could follow the steps for word-level classification outlined in the following repository and save the data from the corresponding feature extraction functions:
https://github.com/norahollenstein/reading-task-classification?tab=readme-ov-file#classification-with-word-level-features

**Comment by hamza13-12** [comment]
Hi, after downloading the entire dataset, I got the following error on running the benchmark script:

File "C:\Users\Hamza\Desktop\ZuCo dataset\zuco-benchmark\src\extract_features.py", line 117, in extract_sentence_features
    sent = dlh.load_matlab_string(f[obj_reference_content]) #save the sentence line 117
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hamza\Desktop\ZuCo dataset\zuco-benchmark\src\data_loading_helpers.py", line 80, in load_matlab_string
    extracted_string = u''.join(chr(c) for c in matlab_extracted_object)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Hamza\Desktop\ZuCo dataset\zuco-benchmark\src\data_loading_helpers.py", line 80, in <genexpr>
    extracted_string = u''.join(chr(c) for c in matlab_extracted_object)
                                ^^^^^^
TypeError: only integer scalar arrays can be converted to a scalar index

I resolved this by changing the matlab_load_string like:

def load_matlab_string(matlab_extracted_object):
    """
    Converts a string loaded from h5py into a python string. Handles both the scenarios where the matlab_extracted_object
    is a bytes object directly (h5py 3.x) or an array of unicode characters (h5py 2.x).
    :param matlab_extracted_object: (h5py) matlab string object or bytes
    :return:
        extracted_string    (str)   translated string
    """
    if isinstance(matlab_extracted_object, bytes):
        # If the object is a bytes object, decode it directly to a string
        extracted_string = matlab_extracted_object.decode('utf-8')
    else:
        # Otherwise, handle it as an array of integers representing characters
        extracted_string = ''.join(chr(c[0]) for c in matlab_extracted_object)

   return extracted_string

**Comment by hamza13-12** [comment]
Also, I am still struggling to set EEG data and corressponding sentences up into a dataframe. Could you provide me with precise modifications to make to your existing code to achieve a dataframe? It really would streamline the whole process for me

**Comment by samuki** [comment]
> Hi, after downloading the entire dataset, I got the following error on running the benchmark script:
> 
> File "C:\Users\Hamza\Desktop\ZuCo dataset\zuco-benchmark\src\extract_features.py", line 117, in extract_sentence_features sent = dlh.load_matlab_string(f[obj_reference_content]) #save the sentence line 117 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Hamza\Desktop\ZuCo dataset\zuco-benchmark\src\data_loading_helpers.py", line 80, in load_matlab_string extracted_string = u''.join(chr(c) for c in matlab_extracted_object) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\Hamza\Desktop\ZuCo dataset\zuco-benchmark\src\data_loading_helpers.py", line 80, in extracted_string = u''.join(chr(c) for c in matlab_extracted_object) ^^^^^^ TypeError: only integer scalar arrays can be converted to a scalar index
> 
> I resolved this by changing the matlab_load_string like:
> 
> def load_matlab_string(matlab_extracted_object): """ Converts a string loaded from h5py into a python string :param matlab_extracted_object: (h5py) matlab string object :return: extracted_string (str) translated string """ extracted_string = ''.join(chr(int(c)) for c in matlab_extracted_object) return extracted_string

Hi, this is probably an issue with your `h5py` version. This error should not occur with version 2.9.0, but it's good that you found a fix.

**Comment by samuki** [comment]
> Also, I am still struggling to set EEG data and corressponding sentences up into a dataframe. Could you provide me with precise modifications to make to your existing code to achieve a dataframe? It really would streamline the whole process for me

Sure, here is an example:  
You could for each subject create a dataframe with the sentences and your target EEG features (e.g. `t_mean`) by initializing the data `df_data = {"sent":[], "t_mean":[]}` at the beginning of the function after [line 96](https://github.com/norahollenstein/zuco-benchmark/blob/5ad276d2d075a30e8a47488cff082df435870ce3/src/extract_features.py#L96), then append the data during the loop, e.g. in [line 211](https://github.com/norahollenstein/zuco-benchmark/blob/5ad276d2d075a30e8a47488cff082df435870ce3/src/extract_features.py#L211) 
```
df_data["sent"].append(sent)
df_data["t_mean"].append(t_mean)
```
and then in the end save the subject features:
```
df = pd.DataFrame(df_data)
df.to_csv(f"{subject}_t_means.csv")
```

**Comment by hamza13-12** [comment]
Thank you for sharing this code example. I have tried this out but I get the folllowing error:

 File "C:\Users\Hamza\Desktop\ZuCo dataset\zuco-benchmark\src\extract_features.py", line 329, in extract_sentence_features
    df = pd.DataFrame(df_data)
         ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\frame.py", line 709, in __init__
    mgr = dict_to_mgr(data, index, columns, dtype=dtype, copy=copy, typ=manager)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\internals\construction.py", line 481, in dict_to_mgr
    return arrays_to_mgr(arrays, columns, index, dtype=dtype, typ=typ, consolidate=copy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\internals\construction.py", line 115, in arrays_to_mgr
    index = _extract_index(arrays)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\pandas\core\internals\construction.py", line 655, in _extract_index
    raise ValueError("All arrays must be of the same length")
    
    It looks like in some iterations of the loop, the value is appended to one list and not the other which leads to different lengths

**Comment by hamza13-12** [comment]
Thank you! This is much appreciated
